version: "2"
services:
  fast_api:
    # command: ["uvicorn", "main:app","--reload", "--host", "0.0.0.0", "--port", "8080"]
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app/:/app
    env_file:
      - ./app/.env
    ports:
      - "8080:8080"
    networks:
      - default